### ISSUE TITLE
Support for .flac files?

### ISSUE THREAD

**Issue by DiegoFleitas** [misterhat/livelook#7]
Hi, very neat project!

I'm having trouble making this work reliably tho, does it only support mp3 files at the moment or am I missing something?

Thanks

**Comment by DiegoFleitas** [comment]
It worked with random searches! 
No idea why did It fail so often, must be something wrong with my setup

**Comment by misterhat** [comment]
Sorry this project is still pretty early :P. The module does use some code to try and open up ports that could be inconsistent. The network also blocks searches with certain artists.
